package files;

public class payload {

		public static String AddPlace() {
			
			return "{\r\n"
					+ "  \"location\": {\r\n"
					+ "    \"lat\": -38.383494,\r\n"
					+ "    \"lng\": 33.427362\r\n"
					+ "  },\r\n"
					+ "  \"accuracy\": 50,\r\n"
					+ "  \"name\": \"Radhika S Testing Academy\",\r\n"
					+ "  \"phone_number\": \"(+91) 983 893 3937\",\r\n"
					+ "  \"address\": \"29, side layout, cohen 09\",\r\n"
					+ "  \"types\": [\r\n"
					+ "    \"shoe park\",\r\n"
					+ "    \"shop\"\r\n"
					+ "  ],\r\n"
					+ "  \"website\": \"http://google.com\",\r\n"
					+ "  \"language\": \"French-IN\"\r\n"
					+ "}\r\n"
					+ "";
		}
		
		public static String CoursePrice() {
			
			return "{\r\n"
					+ "  \"dashboard\": {\r\n"
					+ "    \"purchaseAmount\": 910,\r\n"
					+ "    \"website\": \"rahulshettyacademy.com\"\r\n"
					+ "  },\r\n"
					+ "  \"courses\": [\r\n"
					+ "    {\r\n"
					+ "      \"title\": \"Selenium Python\",\r\n"
					+ "      \"price\": 50,\r\n"
					+ "      \"copies\": 6\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "      \"title\": \"Cypress\",\r\n"
					+ "      \"price\": 40,\r\n"
					+ "      \"copies\": 4\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "      \"title\": \"RPA\",\r\n"
					+ "      \"price\": 45,\r\n"
					+ "      \"copies\": 10\r\n"
					+ "    }\r\n"
					+ "  ]\r\n"
					+ "}";
		}
		
		public static String AddBooksLibrary(String isbn,String aisle) {
			
			String payload = "{\r\n"
					+ "\r\n"
					+ "\"name\":\"Learn Appium Automation with Java\",\r\n"
					+ "\"isbn\":\""+isbn+"\",\r\n"
					+ "\"aisle\":\""+aisle+"\",\r\n"
					+ "\"author\":\"John foe\"\r\n"
					+ "}\r\n"
					+ "";
			return payload;
		}
		
		public static String DeleteBookLibrary(String id) {
			
			String payload = "{\r\n"
					+ " \r\n"
					+ "\"ID\" : \""+id+"\"\r\n"
					+ " \r\n"
					+ "} ";
			return payload;
		}
		
		public static String addObjects() {
			
			String payload =  "{\r\n"
					+ "   \"name\": \"Apple MacBook Air Pro 18\",\r\n"
					+ "   \"data\": {\r\n"
					+ "      \"year\": 2024,\r\n"
					+ "      \"price\": 2500.99,\r\n"
					+ "      \"CPU model\": \"Intel Core i11\",\r\n"
					+ "      \"Hard disk size\": \"2 TB\"\r\n"
					+ "   }\r\n"
					+ "}";
			return payload;
		}
		
		public static String  getObjectsApple() {
			
			String  payload = "[\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"1\",\r\n"
					+ "        \"name\": \"Google Pixel 6 Pro\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"color\": \"Cloudy White\",\r\n"
					+ "            \"capacity\": \"128 GB\"\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"2\",\r\n"
					+ "        \"name\": \"Apple iPhone 12 Mini, 256GB, Blue\",\r\n"
					+ "        \"data\": null\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"3\",\r\n"
					+ "        \"name\": \"Apple iPhone 12 Pro Max\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"color\": \"Cloudy White\",\r\n"
					+ "            \"capacity GB\": 512\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"4\",\r\n"
					+ "        \"name\": \"Apple iPhone 11, 64GB\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"price\": 389.99,\r\n"
					+ "            \"color\": \"Purple\"\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"5\",\r\n"
					+ "        \"name\": \"Samsung Galaxy Z Fold2\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"price\": 689.99,\r\n"
					+ "            \"color\": \"Brown\"\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"6\",\r\n"
					+ "        \"name\": \"Apple AirPods\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"generation\": \"3rd\",\r\n"
					+ "            \"price\": 120\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"7\",\r\n"
					+ "        \"name\": \"Apple MacBook Pro 16\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"year\": 2019,\r\n"
					+ "            \"price\": 1849.99,\r\n"
					+ "            \"CPU model\": \"Intel Core i9\",\r\n"
					+ "            \"Hard disk size\": \"1 TB\"\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"8\",\r\n"
					+ "        \"name\": \"Apple Watch Series 8\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"Strap Colour\": \"Elderberry\",\r\n"
					+ "            \"Case Size\": \"41mm\"\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"9\",\r\n"
					+ "        \"name\": \"Beats Studio3 Wireless\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"Color\": \"Red\",\r\n"
					+ "            \"Description\": \"High-performance wireless noise cancelling headphones\"\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"10\",\r\n"
					+ "        \"name\": \"Apple iPad Mini 5th Gen\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"Capacity\": \"64 GB\",\r\n"
					+ "            \"Screen size\": 7.9\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"11\",\r\n"
					+ "        \"name\": \"Apple iPad Mini 5th Gen\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"Capacity\": \"254 GB\",\r\n"
					+ "            \"Screen size\": 7.9\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"12\",\r\n"
					+ "        \"name\": \"Apple iPad Air\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"Generation\": \"4th\",\r\n"
					+ "            \"Price\": \"419.99\",\r\n"
					+ "            \"Capacity\": \"64 GB\"\r\n"
					+ "        }\r\n"
					+ "    },\r\n"
					+ "    {\r\n"
					+ "        \"id\": \"13\",\r\n"
					+ "        \"name\": \"Apple iPad Air\",\r\n"
					+ "        \"data\": {\r\n"
					+ "            \"Generation\": \"4th\",\r\n"
					+ "            \"Price\": \"519.99\",\r\n"
					+ "            \"Capacity\": \"256 GB\"\r\n"
					+ "        }\r\n"
					+ "    }\r\n"
					+ "]";
			return payload;
		}
}
